apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: icescrum
  name: icescrum
  namespace: icescrum
spec:
  replicas: 1
  selector:
    app: icescrum
    deploymentconfig: icescrum
  template:
    metadata:
      labels:
        app: icescrum
        deploymentconfig: icescrum
    spec:
      containers:
      - image: icescrum/icescrum
        imagePullPolicy: Always
        name: icescrum
